name: Build project
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project
        run: mvn -B -DskipTests=true package --file pom.xml


      - name: Deploy warranty
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: 7c1b05eb-5727-4f65-aa40-5bfb4db10c82
          heroku_app_name: warranty-service-app-zav
          heroku_email: zabava.alex@gmail.com
          healthcheck: https://warranty-service-app-zav.herokuapp.com/manage/health
          usedocker: true
          appdir: warranty
          delay: 70

      - name: Deploy warehouse
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: 7c1b05eb-5727-4f65-aa40-5bfb4db10c82
          heroku_app_name: warehouse-service-app-zav
          heroku_email: zabava.alex@gmail.com
          healthcheck: https://warehouse-service-app-zav.herokuapp.com/manage/health
          usedocker: true
          appdir: warehouse
          delay: 70

      - name: Deploy order
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: 7c1b05eb-5727-4f65-aa40-5bfb4db10c82
          heroku_app_name: order-service-app-zav
          heroku_email: zabava.alex@gmail.com
          healthcheck: https://order-service-app-zav.herokuapp.com/manage/health
          usedocker: true
          appdir: order
          delay: 70

      - name: Deploy store
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: 7c1b05eb-5727-4f65-aa40-5bfb4db10c82
          heroku_app_name: store-service-app-zav
          heroku_email: zabava.alex@gmail.com
          healthcheck: https://store-service-app-zav.herokuapp.com/manage/health
          usedocker: true
          appdir: store
          delay: 70

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
